name: Nightly

on:
  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:

jobs:

  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       versions:
         - IMAGE: michaelruocco/wiremock:nightly
           CONTEXT: .
           PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
         - IMAGE: michaelruocco/wiremock:nightly-alpine
           CONTEXT: alpine
           PLATFORMS: linux/amd64
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: ${{ matrix.versions.CONTEXT != 'alpine' }}
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Checkout sources
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Wiremock Docker image
        run: docker buildx build --tag ${{ matrix.versions.IMAGE }} --load ${{ matrix.versions.CONTEXT }} --file ${{ matrix.versions.CONTEXT }}/Dockerfile-nightly

      - name: Test Wiremock Docker image
        run: |
          # default
          docker container run -d --name test -p 8080:8080 ${{ matrix.versions.IMAGE }}
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/; do sleep 1; done'
          docker container rm -f test
          # args
          docker container run -d --name test -p 8443:8443 ${{ matrix.versions.IMAGE }} --https-port 8443
          timeout 10 bash -c 'while ! curl --fail --insecure https://localhost:8443/__admin/; do sleep 1; done'
          docker container rm -f test
          if [ "${{ matrix.versions.CONTEXT }}" != "alpine" ]
          then
            # helloworld
            docker buildx build --tag wiremock-hello --load samples/hello --file samples/hello/Dockerfile-nightly
            docker container run -d --name test -p 8080:8080 wiremock-hello
            timeout 10 bash -c 'while ! curl --fail http://localhost:8080/hello; do sleep 1; done'
            docker container rm -f test
            # random
            docker buildx build --tag wiremock-random --load samples/random --file samples/random/Dockerfile-nightly
            docker container run -d --name test -p 8080:8080 wiremock-random
            timeout 10 bash -c 'while ! curl --fail http://localhost:8080/random; do sleep 1; done'
            docker container rm -f test
          fi

      - name: Push Wiremock Docker image to Docker HUB
        run: docker buildx build --tag ${{ matrix.versions.IMAGE }} --platform ${{ matrix.versions.PLATFORMS }} --push ${{ matrix.versions.CONTEXT }} --file ${{ matrix.versions.CONTEXT }}/Dockerfile-nightly
